Playground refactor
OpenLiberty/iguide-retry-timeout pull request #103
Opened 2018-06-26 20:41 UTC by kevinwlau

2018-06-29 01:35 UTC, aknguyen7 requested changes
I tested the timeline in the step, after the timeline already run once, click Run on the editor reset the timeline. However click Run on the editor in the playground start a new timeline. Before the refactor changes, click on Run just a no-op in the step. Not sure if this is your intention?

2018-06-29 14:03 UTC, kevinwlau commented
That was unintentional, I've fixed it in the latest commit.

2018-07-17 15:04 UTC, kevinwlau commented
Mentioned verbally a couple weeks ago, the Retry steps only validated the content on the first run, and not subsequent runs. Fixed in faa1815

2018-07-17 15:31 UTC, aknguyen7 approved these changes

2018-07-19 15:05 UTC, merged